### ISSUE TITLE
Radix > 36 raises ValueError

### ISSUE THREAD

**Issue by ghost** [kpdyer/libffx#1]
If I run `benchmark.py --radix 62` it raises a ValueError.

```
Traceback (most recent call last):
  File "benchmark.py", line 68, in <module>
    main()
  File "benchmark.py", line 47, in main
    C = ffx.encrypt(T, M1)
  File "FFX/__init__.py", line 262, in encrypt
    C = self.add(A, self.F(n, T, i, B))
  File "FFX/__init__.py", line 199, in F
    if T == 0:
  File "FFX/__init__.py", line 117, in __eq__
    retval = (self.to_int() == other)
  File "FFX/__init__.py", line 143, in to_int
    self._as_int = int(self._x, self._radix)
ValueError: int() base must be >= 2 and <= 36
```

**Comment by kpdyer** [comment]
Reproduced. Thanks!
